from .websocket import websocket_router
from .auth import auth_router
from .settings import settings_router
from .sessions import sessions_router
from .tts import tts_router
from .relief import relief_router
from .payments import payments_router
from .nepal_payments import nepal_payments_router
from .daily_checks import daily_checks_router